goes-funky/workflows

.github/workflows/build-go.yaml

Ensure that tools and dependencies are always cached regardless of build job result.
Fix cache key for tools to include changes to makefiles/ folder.

feat: separate tools/dependencies cache

---

.github/workflows/deploy-git-flow.yaml
.github/workflows/deploy.yaml
templates/common/deploy.yaml
templates/deploy-git-flow.yaml

Enable skaffold cache - skips docker build if digest of files used in docker image build haven't changed.
Add development-branch input to deploy-git-flow.

feat: skaffold cache

---

Makefile

`make` respects order of operations.

First generate, then lint actions

---

.github/workflows/deploy-git-flow.yaml
.github/workflows/deploy.yaml
templates/common/deploy.yaml

Straightforward workaround for skaffold profiles so that deployments can have different config per environment.
I'm sure this could be done better, but this is the quickest and cleanest I can think of right now.
NOTE: This will break all workflows that use skaffold if they do not have these profiles defined. A more safe approach would be to check a profile is defined in the skaffold.yaml before attempting to activate it on the deploy.

feat: skaffold profiles for environment config nonprod vs prod

---

.github/workflows/build-python.yaml
.github/workflows/deploy-integration.yaml
templates/build-python.yaml
templates/common/deploy-integration.yaml

Issue with GH cache failing for python package installs. This has been occurring occasionally, simplest solution is to always force install the packages even if there is a cache. Only downside is a few more seconds to the build process, but at least this ensures the packages are in place for the circumstance when the cache is failing

feat: force install python deps always

---

.github/workflows/build-go.yaml
.github/workflows/build-python.yaml
.github/workflows/deploy-git-flow.yaml
.github/workflows/deploy-integration.yaml
.github/workflows/deploy.yaml
pkg/common/deploy-integration.cue
pkg/common/deploy.cue
pkg/common/steps.cue
pkg/workflows/build-go.cue
pkg/workflows/build-python.cue

Ignore the ssh-agent task if the repo is flagged as public. In those cases we don't provide the environment so it would fail anyway.

TECH-9424: ignore ssh-agent for public workflows

---

.github/workflows/deploy-git-flow.yaml
.github/workflows/deploy-integration.yaml
.github/workflows/deploy.yaml
pkg/common/deploy-integration.cue
pkg/common/deploy.cue
pkg/common/steps.cue

This seems to work: https://github.com/goes-funky/company-api/actions/runs/3197328490 (save for the deployment stabilizing on the incomplete `qa` cluster).
Three cheers to @nhamlh for the CUE lang migration. It's awesome being able to work on these without as much worry.

TECH-8858: Migrate to the new GCP auth action

---

.github/workflows/deploy-git-flow.yaml
.github/workflows/deploy.yaml
pkg/common/deploy.cue

https://app.clickup.com/t/2575789/TECH-9082
To support a mono-repo deployment, we need multiple skaffold files. With this change we allow users to provide a custom skaffold file name in the config. It will still default to skaffold.yaml for all other repositories.
c.f. https://github.com/goes-funky/y42-frontend/pull/2009

TECH-9082: accept skaffold filename param in deploy flow

---

.github/workflows/build-go.yaml
.github/workflows/build-python.yaml
.github/workflows/deploy-git-flow.yaml
.github/workflows/deploy-integration.yaml
.github/workflows/deploy.yaml
pkg/common/deploy-integration.cue
pkg/common/deploy.cue
pkg/workflows/build-go.cue
pkg/workflows/build-python.cue

https://app.clickup.com/t/2575789/TECH-11304
Upgrade standard github actions to newest major version to fix the set-output warnings.

TECH-11304: upgrade github actions to newest version

---

.github/workflows/deploy-git-flow.yaml
.github/workflows/deploy-integration.yaml
.github/workflows/deploy.yaml
pkg/common/steps.cue

Bump setup-kube-tools version to avoid warnings with regards to set-output calls.

TECH-11304: bump setup-kube-tools version

---

.github/workflows/build-php.yaml
pkg/workflows/build-php.cue

Bump version, because they fix the set-output deprecation warning in 5.2.0.

TECH-11304: bump skip-duplicate-actions version

---

.github/workflows/deploy-git-flow.yaml
.github/workflows/deploy.yaml
pkg/common/deploy.cue

We currently use the git short sha for the Datadog version number. This pr enables skaffold to access this during the build process so we can inject this via Docker into the built container.

TECH-12960: Skaffold build short-sha

---

.github/workflows/build-go.yaml
.github/workflows/build-php.yaml
.github/workflows/build-python.yaml
.github/workflows/deploy-git-flow.yaml
.github/workflows/deploy-integration.yaml
.github/workflows/deploy.yaml
.github/workflows/draft-release.yaml
.github/workflows/workflows.yaml
pkg/common/workflow.cue

Set a default timeout of 15minutes for all workflows that can be overwritten in the individual job configs. This might break some things that happen today, but should be easy to remediate once people complain.
The default timeout is at 6h which seems a bit crazy to me.

TECH-10695: set default timeout for all jobs

---

.github/workflows/deploy-git-flow.yaml
.github/workflows/deploy-integration.yaml
.github/workflows/deploy.yaml
pkg/common/deploy-integration.cue
pkg/common/deploy.cue
pkg/common/steps.cue

The current version of the skaffold cache setup is actually useless as the cache is created on the first action run and is never updated then.
The fix is based on this https://github.com/GoogleContainerTools/skaffold/issues/4842#issuecomment-709423350

TECH-13067: skaffold cache fixes

---

.github/workflows/build-php.yaml
.github/workflows/build-python.yaml
.github/workflows/deploy-git-flow.yaml
.github/workflows/deploy-integration.yaml
.github/workflows/deploy.yaml
pkg/common/deploy-integration.cue
pkg/common/steps.cue
pkg/workflows/build-php.cue

https://app.clickup.com/t/2575789/TECH-12148
- In specific cases the pre-job skips existing runs for php. IMO it's not necessary and it seems to skip _later_ runs. So overall, we should be able to remove it. Also, the action uses the deprecated `set-output` command.
- Upgrade google-github-actions to v1

TECH-12148: remove pre-job on PHP workflows and update google actions to v1

---

.github/workflows/deploy-git-flow.yaml
.github/workflows/deploy.yaml
pkg/common/deploy.cue

No longer attempt to block deploys from the develop branches from going to prod. Now any branch can go to prod.
Previous code was using wrong skaffold profile on prod deploys

TECH-13307: Allow deploy to prod from main

---

.github/workflows/build-php.yaml
pkg/workflows/build-php.cue

Skips PHP build actions on duplicate runs (same treehash). This should speed up deployments and reduce our build costs.

TECH-13448: skip php actions on duplicate runs

---

scripts/docker-buildx

This should fix the issue experienced on https://github.com/goes-funky/low-code-api/actions/runs/3827910890

TECH-13728: fix missing GITHUB_SHA build arg

---

.github/workflows/flux-build.yaml
pkg/common/flux-build.cue

Allow GCR login with flux builds. This exception is only relevant for the modeling-api today.

TECH-13724: increase flux build timeout

---

.github/workflows/build-go.yaml
.github/workflows/build-python.yaml
.github/workflows/deploy-git-flow.yaml
.github/workflows/deploy-integration.yaml
.github/workflows/deploy.yaml
.github/workflows/flux-build.yaml
pkg/common/steps.cue
pkg/workflows/build-go.cue
pkg/workflows/build-python.cue

In https://github.com/goes-funky/dbt-functions/pull/27, we would like to be able to include dbt-utils as a pre-installed package available to dbt projects. @ronozoro proposed to add it as a git submodule, which I agree is a clean way to do it, and better than committing the dbt-utils files directly to the repo. However, our Python build action does not currently fetch submodules (unlike our [Go build actions](https://github.com/goes-funky/workflows/blob/master/.github/workflows/build-go.yaml#L31)). This PR enables it for Python as well.

Fetch submodules in Python project builds

---

.github/workflows/deploy-integration.yaml
pkg/common/deploy-integration.cue

Container Registry in addition to (presumably, but confirmed by GCP
marketing copy and our hunches while looking at the billing console)
being the less economical option, is also being deprecated.
Migrate the integrations to the new Artifact Registry.
This won't affect v1 - those integrations build via Cloud Build, into
the `datos-tech` project.

SRE-415: push integrations to Artifact Registry

---

.github/workflows/build-python.yaml
pkg/common/workflow.cue
pkg/workflows/build-python.cue

This PR _attempts_ to add explicit permission to the `diff_poetry`. The assigned `issues: write` permission is the same as the default permission. Dependabot requires these permissions to be set explicitly. Otherwise, tests on dependabot PRs will always fail when trying to post the PR comment with the version differences.
FYI: PR comments are technically _just_ issue comments.
> By default, GitHub Actions workflows triggered by Dependabot get a GITHUB_TOKEN with read-only permissions. You can use the permissions key in your workflow to increase the access for the token.
[https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#changing-gith[…]en-permissions](https://docs.github.com/en/code-security/dependabot/working-with-dependa …

feat: diff_poetry add explicit permission issues write

---

.github/workflows/build-go.yaml
.github/workflows/build-php.yaml
.github/workflows/build-python.yaml
.github/workflows/deploy-integration.yaml
.github/workflows/workflows.yaml
pkg/common/deploy-integration.cue
pkg/common/steps.cue
pkg/workflows/build-go.cue
pkg/workflows/build-php.cue
pkg/workflows/build-python.cue
pkg/workflows/workflows.cue

Upgrade default action versions to use node 20 instead of (deprecated) node 16.

chore: move node16 actions to node20 version

---

.github/workflows/build-python.yaml
pkg/workflows/build-python.cue

As per https://github.com/SonarSource/sonarcloud-github-action we should switch this action's drop-in replacement `sonarqube-scan-action`

chore(BAC-20): replace the deprecated sonar action
