- .github/workflows/build-python.yaml
Fetch private dependencies over SSH.
Allow for skipping lint and formatting.
Successful run here: https://github.com/goes-funky/orchestration-api/runs/4563326761?check_suite_focus=true
> Use Poetry to install Python packages

- .github/workflows/deploy-git-flow.yaml
- .github/workflows/deploy.yaml
- templates/common/deploy.yaml
> Use a separate service account to push images to GCR

- .github/workflows/build-python.yaml
- templates/build-python.yaml
* Added a test runner and (optional) upload of coverage to codecov
* Added mypy
* Separated build, formatting, linting and testing into separate flows to make it more obvious what is happening, and what might have failed:
> feat: Add coverage to python build

- .github/workflows/deploy-git-flow.yaml
- .github/workflows/deploy-integration.yaml
- .github/workflows/deploy.yaml
- templates/common/deploy-integration.yaml
- templates/common/deploy.yaml
Ignore any passed `gke-location`.
> Use one variable to ID the GKE cluster

- .github/workflows/build-go.yaml
- .github/workflows/build-python.yaml
- .github/workflows/deploy-git-flow.yaml
- .github/workflows/deploy-integration.yaml
- .github/workflows/deploy.yaml
- .github/workflows/draft-release.yaml
- .github/workflows/workflows.yaml
- Makefile
- cue.mod/module.cue
- pkg/common/build.cue
- pkg/common/deploy-integration.cue
- pkg/common/deploy.cue
- pkg/common/workflow.cue
- pkg/workflows/build-go.cue
- pkg/workflows/build-python.cue
- pkg/workflows/deploy-git-flow.cue
- pkg/workflows/deploy-integration.cue
- pkg/workflows/deploy.cue
- pkg/workflows/draft-release.cue
- pkg/workflows/workflows.cue
Using cuelang to generate yaml instead of the current `yq` merge. This has several benefits:
- CUE is a superset of json, think jsonnet. It might seem a bit strange at first but it's easy to learn.
- CUE has stricter type system than YAML so we won't jump into issues e.g when to quote for values like 10 or true. CUE requires all string to be quoted.
- CUE has schema system (think jsonschema) so we can easily validate workflows schema.
- CUE allows us to define objects then reuse it somewhere else. Therefore we can build more proper object for "inheritance" comparing to current `yq` merge. When we reference an object, it's explicit, unlike yq which is implicit and hard to trace on what and where an object merged to generated files.
This PR is the very first part of the process. It only try …
> feat: generate workflows from cuelang

- .github/workflows/build-go.yaml
- .github/workflows/build-python.yaml
- .github/workflows/deploy-git-flow.yaml
- .github/workflows/deploy-integration.yaml
- .github/workflows/deploy.yaml
- pkg/common/build.cue
This reverts commit dae30dd39cd83a3c117c563edf120a548d8120e2.
> Revert "feat: make ssh-private-key optional for python build (#43)"

- .github/workflows/build-python.yaml
- pkg/workflows/build-python.cue
https://app.clickup.com/t/2575789/TECH-9562
Add configuration to automatically perform sonar checks for python workflows. Needs a sonar token as an input and a flag to not skip sonar.
https://github.com/goes-funky/airbyte-message-receiver/pull/7
> TECH-9562: add code scanning and coverage with sonar for python

- .github/workflows/build-go.yaml
- .github/workflows/build-python.yaml
- .github/workflows/deploy-git-flow.yaml
- .github/workflows/deploy-integration.yaml
- .github/workflows/deploy.yaml
- pkg/common/steps.cue
- pkg/workflows/build-python.cue
Sonar uses the history of the current branch for additional checks.
> TECH-9905 increase fetch-depth for python tests

- .github/workflows/build-python.yaml
- pkg/workflows/build-python.cue
I need to run tests for ACL service and it uses docker-compose
so I added two steps before the step which runs pytest
> TECH-10294 run docker-compose up before tests

- .github/workflows/deploy-git-flow.yaml
- .github/workflows/deploy-integration.yaml
- .github/workflows/deploy.yaml
- pkg/common/deploy-integration.cue
- pkg/common/deploy.cue
- pkg/common/steps.cue
configure skaffold to use a custom build script which trigger buildkit, buildkit in turn caches docker image layers to github action cache.
Smoke test: https://github.com/goes-funky/access-control/actions/runs/3059580022/jobs/4937172262
> feat: docker build caching

- .github/workflows/deploy-git-flow.yaml
- .github/workflows/deploy-integration.yaml
- .github/workflows/deploy.yaml
- pkg/common/deploy-integration.cue
- pkg/common/deploy.cue
- pkg/common/steps.cue
This reverts commit 635d8ab3dbb338ac0d6a0f42e63b15c5014dadb0.
Ticket: https://app.clickup.com/t/2575789/TECH-10517
The skaffold manipulation step can't work with all repos and created issue for y42-frontend and lineage-api repo.
> Revert "feat: docker build caching (#53)"

- README.md
Add some small adjustments to the readme file. Overall, it defines the deployment flow quite well, though. 
IMO no pointers to slab necessary.
> TECH-9926: small adjustments to readme file

- .github/workflows/deploy-git-flow.yaml
- .github/workflows/deploy-integration.yaml
- .github/workflows/deploy.yaml
- pkg/common/steps.cue
See https://github.com/goes-funky/lineage-service/actions/runs/3228390847/jobs/5284421641#step:10:19
> TECH-10502: update skaffold to 1.39.2

- .github/workflows/deploy-git-flow.yaml
- .github/workflows/deploy.yaml
- pkg/common/deploy.cue
This reverts commit bdb2033bfcaab8e04b935bbbd428c056fde58690.
> TECH-12092: Revert "fix: move auth step (#65)"

- .github/workflows/build-go.yaml
- .github/workflows/build-php.yaml
- .github/workflows/build-python.yaml
- .github/workflows/deploy-git-flow.yaml
- .github/workflows/deploy-integration.yaml
- .github/workflows/deploy.yaml
- .github/workflows/draft-release.yaml
- .github/workflows/workflows.yaml
- pkg/common/deploy-integration.cue
- pkg/common/deploy.cue
- pkg/workflows/build-go.cue
- pkg/workflows/build-php.cue
- pkg/workflows/build-python.cue
- pkg/workflows/draft-release.cue
- pkg/workflows/workflows.cue
https://app.clickup.com/t/2575789/TECH-11304
> chore: deprecate set-output

- .github/workflows/deploy-git-flow.yaml
- .github/workflows/deploy-integration.yaml
- .github/workflows/deploy.yaml
- pkg/common/steps.cue
to resolve deprecated set-output and save-state directive
https://app.clickup.com/t/2575789/TECH-11304
> chore: bump docker/login-action to v2

- .github/workflows/deploy-git-flow.yaml
- .github/workflows/deploy.yaml
- pkg/common/deploy.cue
https://app.clickup.com/t/2575789/TECH-11649
Make the name of the uploaded artifact dynamic to avoid race conditions and conflicts. Should not require any change in the upstream repos.
> TECH-11649: make build artifact upload name dynamic

- .github/workflows/build-python.yaml
- .github/workflows/deploy-git-flow.yaml
- .github/workflows/deploy-integration.yaml
- .github/workflows/deploy.yaml
- pkg/common/deploy-integration.cue
- pkg/common/deploy.cue
- pkg/common/steps.cue
- pkg/workflows/build-python.cue
https://app.clickup.com/t/2575789/TECH-10695
Authenticate to GCP Artifact Registry in addition to GCR registry.
> TECH-10695: authenticate to gcp artifact registry

- .github/workflows/deploy-git-flow.yaml
- .github/workflows/deploy.yaml
- pkg/common/deploy.cue
Accept a name of a single artifact to untar.
> TECH-12848: untar build artifact

- .github/workflows/build-python.yaml
- pkg/common/steps.cue
- pkg/workflows/build-python.cue
> TECH-13310 build from artifact

- .editorconfig
- pkg/common/deploy-integration.cue
- pkg/common/deploy.cue
- pkg/common/steps.cue
- pkg/common/workflow.cue
- pkg/workflows/build-go.cue
- pkg/workflows/build-php.cue
- pkg/workflows/build-python.cue
- pkg/workflows/deploy-git-flow.cue
- pkg/workflows/deploy-integration.cue
- pkg/workflows/deploy.cue
- pkg/workflows/draft-release.cue
- pkg/workflows/workflows.cue
Who wants to start a tabs vs spaces discussion? ⚔️ 😄
> chore: standardize styling for cue files

- .github/workflows/build-php.yaml
- pkg/workflows/build-php.cue
Rolling back the version as the new one is causing some weird issues.
> TECH-13144: rolling back tj-actions/changed-files to the prev version

- .github/workflows/build-php.yaml
- .github/workflows/build-python.yaml
- pkg/common/steps.cue
- pkg/common/workflow.cue
- pkg/workflows/build-php.cue
- pkg/workflows/build-python.cue
Use trufflehog to scan repository for secrets.
> TECH-12604: add security scans for php and python flows

- .github/workflows/deploy-git-flow.yaml
- .github/workflows/deploy-integration.yaml
- .github/workflows/deploy.yaml
- pkg/common/deploy-integration.cue
- pkg/common/deploy.cue
- pkg/common/steps.cue
Once this is working as intended will move to having the build script located in the workflow repo as well.
> TECH-7759: Docker layer caching on all workflows

- .github/workflows/deploy-git-flow.yaml
- .github/workflows/deploy-integration.yaml
- .github/workflows/deploy.yaml
- pkg/common/deploy-integration.cue
- pkg/common/deploy.cue
- pkg/common/steps.cue
Skaffold build params not being included in builds. Reverting until there is a fix.
> TECH-7759: revert Docker layer caching on all workflows (#95)"

- .github/workflows/deploy-git-flow.yaml
- .github/workflows/deploy.yaml
- pkg/common/deploy.cue
Enforce nonprod deployment to development environments
> TECH-13609: use nonprod environment for dev deploy

- .github/workflows/build-php.yaml
- .github/workflows/build-python.yaml
- pkg/common/steps.cue
Pin version to avoid https://github.com/trufflesecurity/trufflehog/issues/1002 for now.
> TECH-12604: pin trufflehog version

- .github/workflows/build-python.yaml
- pkg/workflows/build-python.cue
see https://github.com/goes-funky/job-info-service/pull/245
> DEL-107 diff poetry.lock

- .github/workflows/build-python.yaml
- pkg/workflows/build-python.cue
Attempt to install poetry packages each time we run python code. This ensures that even if there is a cache miss we always get the fully installed poetry packages.
> TECH-13533: fix poetry package cache misses

- .github/workflows/build-python.yaml
- pkg/common/workflow.cue
- pkg/workflows/build-python.cue
I not found a way to test and now i am muuuuch more confident that this actually works.
Here is a workflow run that used this branch successfully: https://github.com/goes-funky/y42-quart-common/actions/runs/8583338153/job/23522424320?pr=330
> feat: set poetry diff permissions explicitly

- .github/workflows/build-python.yaml
- pkg/common/workflow.cue
- pkg/workflows/build-python.cue
This reverts commit bb9c56b9950215a4618b44703cbf628b486c2fa8.
> Revert "feat: set poetry diff permissions explicitly (#126)"

- .github/workflows/build-python.yaml
- pkg/common/workflow.cue
- pkg/workflows/build-python.cue
This PR adds a new input variable for setting the integration test timeout.
> feat: add integration-test-timeout
